In [ ]:
data is a main important component of data science
data is an input for performing data science

Definition: 
    Bringing insights from data is nothing but data science
    data ===> information
    
Types of data:
    int
    float
    bool
    str==> object
    
    Continueous data
    Discrete data
    Categorical data
        1. Nominal data: where sequence doesnt matter 
            Example: Male,Female
        2. Ordinal data: sequence matters
            Example: High Medium Low
        
    Relationships of data
    

In [ ]:
Data:=
    1. structured data: relational, row X columns, Eg. excel, csv
    2. Unstructured data: multimedia data, eg. image, audio,video

Machine Learning
Deep learning
100=50-60(Py+ds)+25(ML)+20(Deployement)

In [ ]:
Data science libraries:
    1. Numpy: numerical python/used for statistical analysis==> array
    2. Pandas: Data analysis==> 
        1. Series 2. DataFrame
    3. Matplotlib: Data visualization
    4. Seaborn: Data visualization
        
        

# Numpy

In [1]:
import numpy

In [2]:
numpy

<module 'numpy' from '/srv/conda/envs/notebook/lib/python3.6/site-packages/numpy/__init__.py'>

In [4]:
# Main important thing about numpy is:to create an array
help(numpy.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

In [6]:
numpy.array(100)

array(100)

In [7]:
numpy.array([10,20,30])

array([10, 20, 30])

In [10]:
numpy.array((10,20,30))

array([10, 20, 30])

In [11]:
numpy.array({1,2,3,4,1,2})

array({1, 2, 3, 4}, dtype=object)

In [14]:
import numpy as np

### 1 dim array

In [16]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [17]:
a.ndim

1

In [18]:
a.size

3

In [22]:
len(a)

3

In [19]:
a.shape

(3,)

In [20]:
a.dtype

dtype('int64')

In [23]:
type(a)
#interview que: what is type of numpy array?

numpy.ndarray

In [27]:
type(np.array([1,2,3.,'A']))

numpy.ndarray

## 2 dim array

In [32]:
b = np.array([[1.,2.],[3.,4.]])
b

array([[1., 2.],
       [3., 4.]])

In [29]:
b.ndim

2

In [30]:
b.size

4

In [31]:
b.shape#(row,column)

(2, 2)

In [33]:
b.dtype

dtype('float64')

### 3 dim

In [43]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,1,1],[2,2,2],[3,3,3]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [36]:
c.ndim

3

In [44]:
c.shape#(block,row,column)

(2, 3, 3)

In [45]:
# how to convert array to list
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]]])

In [46]:
c.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 1, 1], [2, 2, 2], [3, 3, 3]]]

In [49]:
np.info(np.dtype)

 dtype()

dtype(obj, align=False, copy=False)

Create a data type object.

A numpy array is homogeneous, and contains elements described by a
dtype object. A dtype object can be constructed from different
combinations of fundamental numeric types.

Parameters
----------
obj
    Object to be converted to a data type object.
align : bool, optional
    Add padding to the fields to match what a C compiler would output
    for a similar C-struct. Can be ``True`` only if `obj` is a dictionary
    or a comma-separated string. If a struct dtype is being created,
    this also sets a sticky alignment flag ``isalignedstruct``.
copy : bool, optional
    Make a new copy of the data-type object. If ``False``, the result
    may just be a reference to a built-in data-type object.

See also
--------
result_type

Examples
--------
Using array-scalar type:

>>> np.dtype(np.int16)
dtype('int16')

Structured type, one field name 'f1', containing int16:

>>> np.dtype([('f1', np.int16)])
dtype([('f1', '<i2

In [ ]:
64bit==>8bytes

## Creating arrays using default functions of numpy

In [50]:
# i want to create array with all Zero's
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.zeros((3,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [54]:
#create array with all one's==>1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [56]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [59]:
# want identity matrix/array
# whose diagonal elements are 1
np.eye(5)#returns 2 dim array 5 X 5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [74]:
#np.info(np.eye)
#help(np.eye)
np.eye?

In [61]:
np.arange(6)#==> equivalent to range

array([0, 1, 2, 3, 4, 5])

In [62]:
np.arange(2,21)#end is exclusive

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20])

In [64]:
np.arange(1,101,2)#start,stop, step same as that of range in python

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [67]:
np.arange(11,0,-1)

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [71]:
np.arange(1,12)[::-1]

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])