In [2]:
import numpy as np
a = np.array([1,2])
a

array([1, 2])

In [4]:
a.size

2

In [5]:
a.ndim

1

In [7]:
len(a)

2

In [8]:
a.dtype

dtype('int32')

In [1]:
b=np.array([[1,2],[2,3]])
b

NameError: name 'np' is not defined

In [8]:
import numpy as np
b=np.array([[1,2],[2,3]])
b

array([[1, 2],
       [2, 3]])

In [9]:
b.size


4

In [10]:
b.shape


(2, 2)

In [11]:
b.ndim


2

In [12]:
type(b)

numpy.ndarray

In [13]:
b.dtype

dtype('int32')

In [14]:
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
c

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [15]:
c.ndim


3

In [16]:
c.shape

(1, 3, 3)

In [17]:
d = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
d


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [18]:
d.shape

(2, 3, 3)

In [19]:
d.tolist

<function ndarray.tolist>

In [20]:
d.tolist()

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[11, 12, 13], [14, 15, 16], [17, 18, 19]]]

In [21]:
v=d.tolist()

In [22]:
type(v)

list

In [23]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [24]:
f=d.tostring()

C:\Users\admin\AppData\Local\Temp/ipykernel_4980/1644931165.py:1: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  f=d.tostring()


In [25]:
type(f)

bytes

In [26]:
f

b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x05\x00\x00\x00\x06\x00\x00\x00\x07\x00\x00\x00\x08\x00\x00\x00\t\x00\x00\x00\x0b\x00\x00\x00\x0c\x00\x00\x00\r\x00\x00\x00\x0e\x00\x00\x00\x0f\x00\x00\x00\x10\x00\x00\x00\x11\x00\x00\x00\x12\x00\x00\x00\x13\x00\x00\x00'

In [27]:
f.tobytes()

AttributeError: 'bytes' object has no attribute 'tobytes'

In [28]:
d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[11, 12, 13],
        [14, 15, 16],
        [17, 18, 19]]])

# Homework

In [8]:
# I want to create 4x4 array which will contain all True values
import numpy as np
np.ones((4,4),dtype='bool')

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

# I want to create array which will contain all False values
np.zeros((4,4),dtype='bool')

In [17]:
# I want to create 5x5 array in which Diagonal values should be True & non diagonal values should be False

v = np.eye((5),dtype='bool')
v

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

# Indexing and Slicing

In [18]:
import numpy as np
a=np.array([[1,2,3],
            [4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a.ndim

2

In [20]:
a.shape

(3, 3)

In [21]:
a[0]

array([1, 2, 3])

In [22]:
a[0:0]

array([], shape=(0, 3), dtype=int32)

In [23]:
a[0][1]

2

In [24]:
id(a)

2724216405616

In [25]:
b =np.array([[1,2,3,4],
            [5,6,7,8],[9,10,11,12]])

In [26]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
b[2,2]

11

In [28]:
b[2,2]=13
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 13, 12]])

In [29]:
b[2,2]=11

In [30]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
b[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [32]:
b[::1]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
b[::]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
b[::3]

array([[1, 2, 3, 4]])

In [35]:
b[1::2]

array([[5, 6, 7, 8]])

In [42]:
b[:,:1]

array([[1],
       [5],
       [9]])

In [37]:
b[:,]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
b[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [39]:
b[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [40]:
b[:,::4]

array([[1],
       [5],
       [9]])

In [43]:
b[:,::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [44]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
b[::-1,:]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [46]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
b[1,1:3:-1]

array([], dtype=int32)

In [48]:
b[1:2,1:3:-1]

array([], shape=(1, 0), dtype=int32)

In [49]:
b[1,1:3][::-1]

array([7, 6])

# Homework
## Access the corner elements
## change the corner elements to 0

In [50]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
b[::2,::3]=0

In [52]:
b

array([[ 0,  2,  3,  0],
       [ 5,  6,  7,  8],
       [ 0, 10, 11,  0]])

In [53]:
b[0]=b[0,3]=b[2,0]=b[2,3]=0

In [54]:
b

array([[ 0,  0,  0,  0],
       [ 5,  6,  7,  8],
       [ 0, 10, 11,  0]])

In [58]:
b[1,1]=1

In [59]:
b

array([[ 0,  0,  0,  0],
       [ 0,  1,  0,  0],
       [ 0, 10, 11,  0]])

In [60]:
a=np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# # access 6,7 10,11==>1,2,3,4

In [61]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
a[1:,1:3]=[1,2],[4,3]
a

array([[ 1,  2,  3,  4],
       [ 5,  1,  2,  8],
       [ 9,  4,  3, 12]])

# # access 2,4 10,12 ==> 'A'

In [79]:
a=np.array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]],dtype='str')
a

array([['1', '2', '3', '4'],
       ['5', '6', '7', '8'],
       ['9', '10', '11', '12']], dtype='<U2')

In [80]:
a[::2,1::2]='A'

In [81]:
a

array([['1', 'A', '3', 'A'],
       ['5', '6', '7', '8'],
       ['9', 'A', '11', 'A']], dtype='<U2')

# i want to access 1,2 4 column

In [82]:
a=np.array([[ 1,  2,  3,  4],
       [ 5,  1,  2,  8],
       [ 9,  4,  3, 12]])

In [83]:
a

array([[ 1,  2,  3,  4],
       [ 5,  1,  2,  8],
       [ 9,  4,  3, 12]])

In [87]:
a[:,[0,1,3]]

array([[ 1,  2,  4],
       [ 5,  1,  8],
       [ 9,  4, 12]])

# i want to access 1,3,4 column

In [88]:
a[:,[0,2,3]]

array([[ 1,  3,  4],
       [ 5,  2,  8],
       [ 9,  3, 12]])

# Vector math in numpy

In [90]:
x=np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [92]:
y=np.array([[2,3],[4,5]])
y

array([[2, 3],
       [4, 5]])

In [93]:
x+y

array([[3, 4],
       [6, 7]])

In [94]:
x+=y

In [95]:
x

array([[3, 4],
       [6, 7]])

In [96]:
y

array([[2, 3],
       [4, 5]])

In [97]:
np.subtract(y,x)

array([[-1, -1],
       [-2, -2]])

In [98]:
np.subtract(x,y)

array([[1, 1],
       [2, 2]])

In [106]:
v=np.full((5,5),0,dtype='int16')

In [113]:
np.fill_diagonal(v,2,wrap='True')

In [114]:
v

array([[2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2]], dtype=int16)

# aggregate function

In [115]:
a=np.array([[ 0,  2],
       [ 1,  4],
       [11, 22],
       [23, 65]])
a

array([[ 0,  2],
       [ 1,  4],
       [11, 22],
       [23, 65]])

In [116]:
np.std(a)

20.40833163195855

In [117]:
np.sum(a)

128

In [119]:
np.max(a,axis=1)

array([ 2,  4, 22, 65])

In [130]:
np.sum(a[:,:])

4

# Reshape in numpy

In [3]:
import numpy as np
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [4]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
a.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [7]:
b = np.array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [8]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [9]:
b.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [10]:
b


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [11]:
b[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
b[0].reshape(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a.reshape(4,-1)#if we dont konw no of coluns then use -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [15]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [17]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [19]:
b.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

# Ravel

In [34]:
b.ravel('F')

array([ 0, 10,  2, 12,  4, 14,  6, 16,  8, 18,  1, 11,  3, 13,  5, 15,  7,
       17,  9, 19])

In [22]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [36]:
import numpy as np

a = np.array([(1,2,3,4),(3,1,4,2)])

print ("Original array:\n ")
print(a)
print ("Dimension of array-> " , (a.ndim))
print("\nOutput for RAVEL \n")
b = a.ravel()
print(b)
b[0]=1000
print(b)
print(a)
print ("Dimension of array->" ,(b.ndim))
print("\nOutput for FLATTEN \n")
c = a.flatten()
print(c)
c[0]=0
print(c)
print(a)

print ("Dimension of array-> " , (c.ndim))


Original array:
 
[[1 2 3 4]
 [3 1 4 2]]
Dimension of array->  2

Output for RAVEL 

[1 2 3 4 3 1 4 2]
[1000    2    3    4    3    1    4    2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array-> 1

Output for FLATTEN 

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array->  1


In [37]:
a

array([[1000,    2,    3,    4],
       [   3,    1,    4,    2]])

In [38]:
a=np.arange(20)

In [39]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
a.resize(5,4)

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
a.resize(20)

In [43]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
a.shape=(2,5,2)

In [45]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [46]:
a.shape=(20)

In [47]:
A

NameError: name 'A' is not defined

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
a.shape=(2,-1)

In [50]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [51]:
a.T

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [53]:
np.transpose(a)

array([[ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13],
       [ 4, 14],
       [ 5, 15],
       [ 6, 16],
       [ 7, 17],
       [ 8, 18],
       [ 9, 19]])

In [54]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [55]:
a=np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [66]:
a[4] = np.array([[10],[20],[30],[40]])

ValueError: could not broadcast input array from shape (4,1) into shape (4,)

In [67]:
np.append(a,[10,20,30,40,50])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 10, 20, 30, 40, 50])

In [68]:
a.size

20

In [69]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [73]:
np.append(a,[[10],[20],[30],[40],[50]],axis=1) #adding values in the rows but refelected in coloumn

array([[ 0,  1,  2,  3, 10],
       [ 4,  5,  6,  7, 20],
       [ 8,  9, 10, 11, 30],
       [12, 13, 14, 15, 40],
       [16, 17, 18, 19, 50]])

In [74]:
np.append(a,[[10,20,30,40]],axis=0) #adding values in the colunmn but refelcted in rows

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [10, 20, 30, 40]])

In [75]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [76]:
b=a.ravel()

In [77]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
np.insert(b,3,20)

array([ 0,  1,  2, 20,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19])

In [83]:
np.insert(b,20,200)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19, 200])

## Assignment: Insert the values in between according to axis

In [84]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [85]:
np.insert(a, [1], [[11],[21],[3],[40],[50]], axis=1)

array([[ 0, 11,  1,  2,  3],
       [ 4, 21,  5,  6,  7],
       [ 8,  3,  9, 10, 11],
       [12, 40, 13, 14, 15],
       [16, 50, 17, 18, 19]])

In [86]:
np.insert(a, [3], [66,81,92,73], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [66, 81, 92, 73],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [87]:
np.delete(b,3)

array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [89]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [91]:
np.delete(a,[1,6,19,4,8,11])

array([ 0,  2,  3,  5,  7,  9, 10, 12, 13, 14, 15, 16, 17, 18])

In [92]:
np.delete(a,np.s_[:11])

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

## Assignment: Delete the rows and columns in between according to axis# 

In [93]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [94]:
np.delete(a,[2],axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [95]:
np.delete(a,[3],axis=1)

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])