In [1]:
import numpy as np

In [6]:
a = np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
a.resize(4,6)

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [13]:
np.where(a<10,a+100,a-10)

array([[100, 101, 102, 103, 104, 105],
       [106, 107, 108, 109,   0,   1],
       [  2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12,  13]])

In [19]:
#without x and y
np.where(a<10)

(array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1]), array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3]))

In [16]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [21]:
a[1,3]

9

In [23]:
a[a<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
list(filter(lambda x:x<10,a.ravel()))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [27]:
np.array(list(filter(lambda x:x<10,a.ravel())))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
b= np.arange(1,22)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [29]:
b.cumsum()

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190, 210, 231])

In [30]:
c = np.array([2000,4500,6000])
c

array([2000, 4500, 6000])

In [31]:
c.cumsum()

array([ 2000,  6500, 12500])

In [ ]:
2,4,10=16

#### Cricket score board is an example of cumsum


In [32]:
runs = np.array([0,10,2,4,6,10,23])
runs#runs per over

array([ 0, 10,  2,  4,  6, 10, 23])

In [33]:
#Return the cumulative sum of the elements along the given axis
runs.cumsum()

array([ 0, 10, 12, 16, 22, 32, 55])

In [35]:
runs.cumprod()

array([0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.fill_diagonal()

In [ ]:
np.loadtxt()

In [36]:
v = np.array(['HR','Admin','Dev','Dev','Admin','MD','CEO','Dev','Tester'])


In [37]:
v

array(['HR', 'Admin', 'Dev', 'Dev', 'Admin', 'MD', 'CEO', 'Dev', 'Tester'],
      dtype='<U6')

In [38]:
#skip repeated values
np.unique(v)

array(['Admin', 'CEO', 'Dev', 'HR', 'MD', 'Tester'], dtype='<U6')

In [39]:
len(v)

9

In [40]:
len(np.unique(v))

6

In [42]:
np.unique(v).size

6

In [43]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [44]:
list(a)

[array([0, 1, 2, 3, 4, 5]),
 array([ 6,  7,  8,  9, 10, 11]),
 array([12, 13, 14, 15, 16, 17]),
 array([18, 19, 20, 21, 22, 23])]

In [47]:
print(list(a.ravel()))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


In [48]:
a.tolist()

[[0, 1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10, 11],
 [12, 13, 14, 15, 16, 17],
 [18, 19, 20, 21, 22, 23]]

In [50]:
print(a.ravel().tolist())

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


In [51]:
a.itemsize

8

In [52]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [53]:
a.dtype

dtype('int64')